### ISSUE TITLE
Implement Unified Threat Intelligence Scoring with Configurable API Weighting

### ISSUE THREAD

**Issue by dandye** [dandye/adk_runbooks#22]
# Unified Threat Intelligence Scoring System

## Problem Statement

Security teams often have access to multiple threat intelligence sources (VirusTotal, Chronicle, AlienVault, ThreatConnect, etc.), each providing their own threat scores with different scales, methodologies, and reliability levels. This creates several challenges:

- **Inconsistent Scoring**: Different APIs use different scales (0-10, 0-100, categorical ratings)
- **Manual Correlation**: Analysts must manually check multiple sources and mentally weight the results
- **Source Reliability Variance**: Some sources are more reliable for certain IOC types
- **Time Consuming**: Checking multiple APIs sequentially is slow and error-prone
- **No Unified View**: No single "confidence score" that incorporates all available intelligence

## Proposed Solution: Weighted Threat Intelligence Aggregator

Create an intelligent system that:
1. **Discovers** available threat intelligence APIs through SOAR integrations
2. **Queries** multiple sources in parallel for IOCs
3. **Normalizes** scores from different APIs to a common scale
4. **Applies** user-configured weights based on source reliability
5. **Generates** a unified threat score with confidence metrics
6. **Explains** the scoring rationale for analyst review

### 1. API Discovery and Configuration

```python
class ThreatIntelAggregator:
    async def discover_available_apis(self):
        """Automatically discover available threat intel APIs"""
        
        # Check SOAR integrations
        soar_apis = await self.discover_soar_integrations()
        
        # Check MCP tool connections  
        mcp_apis = await self.discover_mcp_tools()
        
        # Check direct API configurations
        direct_apis = await self.load_direct_api_configs()
        
        return self.merge_api_capabilities(soar_apis, mcp_apis, direct_apis)
```

### 2. Dynamic API Capability Detection

```yaml
api_capabilities:
  virustotal:
    supported_ioc_types: [hash, domain, ip, url]
    score_range: [0, 100]
    score_type: "malicious_ratio"
    reliability_factors:
      - detection_count
      - vendor_reputation
      - submission_recency
    
  chronicle_gti:
    supported_ioc_types: [hash, domain, ip]
    score_range: [0, 10] 
    score_type: "confidence_level"
    reliability_factors:
      - google_threat_analysis
      - prevalence_data
      - temporal_analysis
      
  alienvault_otx:
    supported_ioc_types: [hash, domain, ip, url]
    score_range: [1, 5]
    score_type: "threat_level"
    reliability_factors:
      - pulse_reputation
      - community_validation
      - indicator_age
      
  threatconnect:
    supported_ioc_types: [hash, domain, ip, email]
    score_range: [0, 1000]
    score_type: "confidence_score"
    reliability_factors:
      - source_credibility
      - analytic_confidence
      - collection_method
```

### 3. Configurable Weighting System

```yaml
threat_scoring_config:
  # Global API weights (sum should equal 1.0)
  api_weights:
    virustotal: 0.35
    chronicle_gti: 0.40
    alienvault_otx: 0.15
    threatconnect: 0.10
    
  # IOC-type specific weight overrides
  ioc_specific_weights:
    hash:
      virustotal: 0.50  # VT is excellent for file analysis
      chronicle_gti: 0.30
      alienvault_otx: 0.10
      threatconnect: 0.10
      
    domain:
      chronicle_gti: 0.45  # Google DNS data advantage
      virustotal: 0.30
      alienvault_otx: 0.15
      threatconnect: 0.10
      
    ip:
      threatconnect: 0.35  # Strong IP reputation data
      chronicle_gti: 0.35
      virustotal: 0.20
      alienvault_otx: 0.10
  
  # Reliability modifiers based on response quality
  quality_modifiers:
    high_confidence_threshold: 0.85
    medium_confidence_threshold: 0.60
    low_confidence_threshold: 0.30
    
    # Boost weight if API provides high-quality response
    quality_boost_factor: 1.2
    # Reduce weight if API provides low-quality response  
    quality_penalty_factor: 0.8
```

### 4. Parallel Query and Normalization Engine

```python
class ThreatScoreAggregator:
    async def get_unified_threat_score(self, ioc: str, ioc_type: str) -> ThreatScore:
        """Get unified threat score from multiple sources"""
        
        # Identify applicable APIs for this IOC type
        applicable_apis = self.get_apis_for_ioc_type(ioc_type)
        
        # Query all APIs in parallel
        async with asyncio.TaskGroup() as tg:
            tasks = {
                api_name: tg.create_task(self.query_api(api_name, ioc, ioc_type))
                for api_name in applicable_apis
            }
        
        # Collect and normalize results
        normalized_scores = {}
        quality_metrics = {}
        
        for api_name, task in tasks.items():
            try:
                result = task.result()
                normalized_scores[api_name] = self.normalize_score(result, api_name)
                quality_metrics[api_name] = self.assess_response_quality(result)
            except Exception as e:
                self.log_api_failure(api_name, e)
                continue
        
        # Apply configured weights with quality adjustments
        weighted_score = self.calculate_weighted_score(
            scores=normalized_scores,
            qualities=quality_metrics,
            ioc_type=ioc_type
        )
        
        return ThreatScore(
            unified_score=weighted_score.final_score,
            confidence=weighted_score.confidence,
            source_breakdown=normalized_scores,
            quality_assessment=quality_metrics,
            explanation=self.generate_explanation(weighted_score)
        )
```

### 5. Score Normalization Framework

```python
class ScoreNormalizer:
    """Normalize scores from different APIs to 0-100 scale"""
    
    def normalize_virustotal(self, vt_result):
        """VT: ratio of engines marking as malicious"""
        if vt_result.positives == 0:
            return 0
        ratio = vt_result.positives / vt_result.total
        return min(100, ratio * 100)
    
    def normalize_chronicle(self, gti_result):
        """Chronicle: 0-10 confidence to 0-100"""
        return gti_result.confidence_score * 10
    
    def normalize_alienvault(self, otx_result):
        """AlienVault: 1-5 threat level to 0-100"""
        level_map = {1: 10, 2: 30, 3: 50, 4: 75, 5: 100}
        return level_map.get(otx_result.threat_level, 0)
    
    def normalize_threatconnect(self, tc_result):
        """ThreatConnect: 0-1000 confidence to 0-100"""
        return min(100, tc_result.confidence / 10)
```

### 1. Web-Based Configuration UI

```html
<\!-- Threat Intel Configuration Panel -->
<div class="threat-intel-config">
  <h2>Threat Intelligence Scoring Configuration</h2>
  
  <\!-- Available APIs Detection -->
  <section class="api-discovery">
    <h3>Available APIs</h3>
    <button onclick="discoverAPIs()">🔍 Auto-Discover APIs</button>
    
    <div class="api-list">
      <div class="api-item">
        ✅ VirusTotal (SOAR Integration)
        <span class="api-status">Healthy - 1.2s avg response</span>
      </div>
      <div class="api-item">
        ✅ Chronicle GTI (MCP Tool)
        <span class="api-status">Healthy - 0.8s avg response</span>
      </div>
      <div class="api-item">
        ⚠️ AlienVault OTX (Direct API)
        <span class="api-status">Rate Limited - 3.5s avg response</span>
      </div>
      <div class="api-item">
        ❌ ThreatConnect (Not Configured)
        <span class="api-status">API Key Required</span>
      </div>
    </div>
  </section>
  
  <\!-- Weight Configuration -->
  <section class="weight-config">
    <h3>API Weights Configuration</h3>
    
    <div class="weight-sliders">
      <div class="weight-item">
        <label>VirusTotal</label>
        <input type="range" min="0" max="100" value="35" id="vt-weight">
        <span class="weight-value">35%</span>
      </div>
      <div class="weight-item">
        <label>Chronicle GTI</label>
        <input type="range" min="0" max="100" value="40" id="gti-weight">
        <span class="weight-value">40%</span>
      </div>
      <\!-- Auto-adjust other weights to maintain 100% total -->
    </div>
    
    <div class="weight-validation">
      Total Weight: <span id="total-weight">100%</span> ✅
    </div>
  </section>
  
  <\!-- IOC-Specific Overrides -->
  <section class="ioc-overrides">
    <h3>IOC-Type Specific Weights</h3>
    <div class="ioc-tabs">
      <button class="tab active" data-ioc="hash">File Hashes</button>
      <button class="tab" data-ioc="domain">Domains</button>
      <button class="tab" data-ioc="ip">IP Addresses</button>
      <button class="tab" data-ioc="url">URLs</button>
    </div>
    <\!-- Weight sliders for each IOC type -->
  </section>
</div>
```

### 2. YAML Configuration Export/Import

```yaml
# Example exported configuration
threat_intel_config:
  version: "1.0"
  created: "2024-01-15T10:30:00Z"
  
  discovered_apis:
    - name: "virustotal"
      source: "soar_integration"
      status: "active"
      avg_response_time: "1.2s"
      
    - name: "chronicle_gti" 
      source: "mcp_tool"
      status: "active"
      avg_response_time: "0.8s"
      
  global_weights:
    virustotal: 0.35
    chronicle_gti: 0.40
    alienvault_otx: 0.15
    threatconnect: 0.10
    
  ioc_specific_weights:
    hash:
      virustotal: 0.50
      chronicle_gti: 0.30
      alienvault_otx: 0.10
      threatconnect: 0.10
      
  quality_settings:
    enable_quality_adjustment: true
    quality_boost_factor: 1.2
    quality_penalty_factor: 0.8
    min_apis_required: 2
```

### 1. Detailed Score Response

```json
{
  "ioc": "malicious-domain.com",
  "ioc_type": "domain",
  "unified_threat_score": 78.5,
  "confidence": 0.92,
  "query_timestamp": "2024-01-15T14:30:00Z",
  
  "source_breakdown": {
    "virustotal": {
      "raw_score": "15/89 engines",
      "normalized_score": 16.9,
      "weight_applied": 0.30,
      "contribution": 5.1,
      "response_time": "1.1s",
      "quality": "high"
    },
    "chronicle_gti": {
      "raw_score": "8.5/10 confidence",
      "normalized_score": 85.0,
      "weight_applied": 0.45,
      "contribution": 38.3,
      "response_time": "0.7s", 
      "quality": "high"
    },
    "alienvault_otx": {
      "raw_score": "4/5 threat level",
      "normalized_score": 75.0,
      "weight_applied": 0.15,
      "contribution": 11.3,
      "response_time": "2.8s",
      "quality": "medium"
    },
    "threatconnect": {
      "raw_score": "850/1000 confidence",
      "normalized_score": 85.0,
      "weight_applied": 0.10,
      "contribution": 8.5,
      "response_time": "1.5s",
      "quality": "high"
    }
  },
  
  "quality_assessment": {
    "total_apis_queried": 4,
    "successful_responses": 4,
    "avg_response_time": "1.5s",
    "confidence_factors": [
      "All APIs agree on high threat level",
      "Multiple detection sources",
      "Recent threat intelligence data",
      "High source reliability"
    ]
  },
  
  "explanation": {
    "summary": "High threat score driven primarily by Chronicle GTI intelligence",
    "key_factors": [
      "Chronicle GTI shows 85% confidence (38.3 point contribution)",
      "ThreatConnect corroborates with 85% score (8.5 points)",
      "VirusTotal shows limited detection but consistent with threat level",
      "All sources agree this is a malicious domain"
    ],
    "recommendations": [
      "Block domain at network level",
      "Investigate any internal connections to this domain",
      "Add to threat intelligence feeds"
    ]
  }
}
```

### 2. Quick Score for API Integration

```json
{
  "ioc": "malicious-domain.com",
  "unified_score": 78.5,
  "confidence": 0.92,
  "threat_level": "HIGH",
  "recommendation": "BLOCK"
}
```

### Approach 1: SOAR Integration Discovery
```python
async def discover_via_soar(self):
    """Discover threat intel APIs through existing SOAR platform"""
    
    soar_integrations = await self.soar_client.list_integrations()
    
    threat_intel_apis = []
    for integration in soar_integrations:
        if integration.category == "threat_intelligence":
            api_config = await self.extract_api_config(integration)
            threat_intel_apis.append(api_config)
    
    return threat_intel_apis
```

### Approach 2: MCP Tool Discovery
```python
async def discover_via_mcp(self):
    """Discover threat intel capabilities through MCP tools"""
    
    mcp_tools = await self.get_available_mcp_tools()
    
    threat_intel_tools = []
    for tool in mcp_tools:
        if hasattr(tool, 'threat_intel_capability'):
            capability = await tool.get_threat_intel_capability()
            threat_intel_tools.append(capability)
    
    return threat_intel_tools
```

### Approach 3: Direct API Configuration
```python
async def configure_direct_apis(self):
    """Allow manual configuration of direct API connections"""
    
    return {
        "virustotal": {
            "api_key": os.getenv("VT_API_KEY"),
            "endpoint": "https://www.virustotal.com/api/v3"
        },
        "alienvault": {
            "api_key": os.getenv("OTX_API_KEY"), 
            "endpoint": "https://otx.alienvault.com/api/v1"
        }
    }
```

### 1. Analyst Workflow Integration
```python
# In existing threat analysis workflow
threat_score = await threat_intel_aggregator.get_unified_score(
    ioc="suspicious-domain.com",
    ioc_type="domain"
)

if threat_score.unified_score > 70:
    await auto_block_ioc(ioc)
    await create_high_priority_alert(threat_score)
elif threat_score.unified_score > 40:
    await create_investigation_task(threat_score)
```

### 2. Detection Rule Enhancement
```yaml
# Enhanced detection rule with unified scoring
detection:
  selection:
    EventID: 3
    DestinationHostname: "*"
  condition: selection
  
enrichment:
  - type: "unified_threat_score"
    field: "DestinationHostname"
    threshold: 50
    
response:
  - if: "unified_threat_score > 80"
    action: "auto_block"
  - if: "unified_threat_score > 50"  
    action: "create_alert"
```

## Success Metrics

- [ ] **Speed**: 5x faster than manual multi-source checking
- [ ] **Accuracy**: 15% improvement in threat detection through weighted scoring
- [ ] **Coverage**: Support for 5+ major threat intel APIs
- [ ] **Usability**: <5 minute configuration time for new APIs
- [ ] **Reliability**: 99% uptime with automatic failover

## Open Questions

1. **Dynamic Weight Adjustment**: Should the system learn optimal weights based on accuracy over time?

2. **Real-time Reconfiguration**: How do we handle weight changes without disrupting active investigations?

3. **API Cost Management**: Should we factor API costs into the weighting decisions?

4. **Confidence Calibration**: How do we validate that our unified confidence scores are accurate?

5. **Vendor Lock-in**: How do we ensure the system works even if key APIs become unavailable?

6. **False Positive Handling**: How do we adjust weights when APIs consistently provide false positives?

This unified threat scoring system would provide security teams with a single, reliable threat score that incorporates all available intelligence sources while being completely configurable to their specific environment and API availability.

🤖 Generated with [Claude Code](https://claude.ai/code)

Co-Authored-By: Claude <noreply@anthropic.com>
